#!/bin/bash

echo OBSOLETE EXAMPLE FOR HOW TO COMPILE THESE CLI FILES
echo Exiting...
exit

# The legacy build process put object and lib files in ${STARE_HOME}/unix.

# STARE_HOME=/Users/mrilee/git/stare
STARE_HOME=~/stare

CFLAGS_FROM_CONFIGURE_SCRIPT=" -O3 -g -fPIC -Wall -I${INCDIR} -D_BOOL_EXISTS -D__unix -UDIAGNOSE "
CFLAGS_BASE=${CFLAGS_FROM_CONFIGURE_SCRIPT}
#CFLAGS=" -c ${CFLAGS_BASE} "
CFLAGS=" ${CFLAGS_BASE} "
CXX_FLAGS=" -std=c++11 ${CFLAGS} "
CLX_FLAGS=" -std=c++11 "

g++ \
    -o winter2010blizzard_csv_to_STARE \
    ${STARE_HOME}/unix/*.o \
  ${CXX_FLAGS} \
  -I${STARE_HOME}/include \
  -L${STARE_HOME}/unix \
  -lSTARE \
  winter2010blizzard_csv_to_STARE.cpp

g++ \
    -o siblings \
    ${STARE_HOME}/unix/*.o \
  ${CXX_FLAGS} \
  -I${STARE_HOME}/include \
  -L${STARE_HOME}/unix \
  -lSTARE \
  siblings.cpp

g++ \
    -o parent \
    ${STARE_HOME}/unix/*.o \
  ${CXX_FLAGS} \
  -I${STARE_HOME}/include \
  -L${STARE_HOME}/unix \
  -lSTARE \
  parent.cpp

g++ \
    -o children \
    ${STARE_HOME}/unix/*.o \
  ${CXX_FLAGS} \
  -I${STARE_HOME}/include \
  -L${STARE_HOME}/unix \
  -lSTARE \
  children.cpp
